name: Run Playwright Tests from External Repo

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Application Repo
        uses: actions/checkout@v4

      - name: Clone Playwright Test Repository
        run: git clone https://github.com/SickPython/playwright-course.git tests

      - name: Install Dependencies (Uses Existing package.json)
        run: npm install  # This works now since package.json exists

      - name: Run Playwright Tests
        run: npx playwright test tests/

      - name: Upload Playwright Test Report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
