name: Run Playwright Tests from External Repo

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Application Repo
        uses: actions/checkout@v4

      - name: Clone Playwright Test Repository
        run: git clone https://github.com/SickPython/playwright-course.git tests

      - name: Initialize Node.js Project (If Missing)
        run: |
          if [ ! -f package.json ]; then
            npm init -y
          fi

      - name: Install Playwright Dependencies
        run: npm install @playwright/test  # Install Playwright package

      - name: Install Playwright Browsers (With Permissions Fix)
        run: npx --yes playwright install  # Ensures Playwright has execution permissions

      - name: Run Playwright Tests
        run: npx playwright test tests/  # Run Playwright tests

      - name: Upload Playwright Test Report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
