name: Trigger Playwright Tests

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Playwright Test Workflow
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.TEST_REPO_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/your-org/playwright-tests-repo/actions/workflows/playwright.yml/dispatches \
          -d '{"ref":"main"}'
