name: Run Playwright Tests from External Repo

on:
  push:
    branches:
      - main  # Runs tests on push to main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Application Repo
        uses: actions/checkout@v4  # Updated to latest version

      - name: Clone Playwright Test Repository
        run: git clone https://github.com/SickPython/playwright-course.git tests

      - name: Install Dependencies
        run: npm install  # Ensure app dependencies are installed

      - name: Install Playwright
        run: npm install @playwright/test

      - name: Start Application
        run: npm start &  # Runs the application in the background

      - name: Run Playwright Tests
        run: npx playwright test tests/  # Runs Playwright tests from cloned test repo

      - name: Upload Playwright Test Report
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: playwright-report
          path: playwright-report/
