name: Run Playwright Tests on Windows

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest  # Use Windows runner

    steps:
      - name: Checkout Application Repo
        uses: actions/checkout@v4

      - name: Clone Playwright Test Repository
        run: git clone https://github.com/SickPython/playwright-course.git tests

      - name: Set Execution Policy (Fix Permission Issues)
        run: Set-ExecutionPolicy Bypass -Scope Process -Force
        shell: pwsh  # Run in PowerShell

      - name: Install Dependencies
        run: npm install  # Install Playwright and dependencies

      - name: Install Playwright Browsers
        run: npx playwright install  #
